FROM progrium/busybox

ENV NODE_VERSION=%%NODE_VERSION%% CMD=node DOMAIN=nodejs.org

# pull down node
RUN \
  opkg-install curl libstdcpp && \
  rm -f /lib/libpthread.so.0 && \
  ln -s /lib/libpthread-2.18.so /lib/libpthread.so.0 && \
  curl -s http://${DOMAIN}/dist/v${NODE_VERSION}/${CMD}-v${NODE_VERSION}-linux-x64.tar.gz | gunzip | tar -xf - -C /

# cleanup
RUN \
  rm -rf /${CMD}-v${NODE_VERSION}-linux-x64/lib && \
  rm /${CMD}-v${NODE_VERSION}-linux-x64/*.md && \
  rm ${CMD}-v${NODE_VERSION}-linux-x64.tar.gz

ENV PATH /${CMD}-v${NODE_VERSION}-linux-x64/bin:$PATH

# define how to run the image
CMD [ "node" ]
